/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OrderPeriodModelsPeriodShippingDetail : Data carrier for a shipping detail



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderPeriodModelsPeriodShippingDetail {
    /// Unique identifier for this shipping detail
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Id of the sipping method
    #[serde(rename = "ShippingId", skip_serializing_if = "Option::is_none")]
    pub shipping_id: Option<i32>,
    /// Name of the shipping method
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Parcel number (tracking number)
    #[serde(rename = "ParcelNumber", skip_serializing_if = "Option::is_none")]
    pub parcel_number: Option<String>,
    /// Shipping date
    #[serde(rename = "ShippingDate", skip_serializing_if = "Option::is_none")]
    pub shipping_date: Option<String>,
    /// Tracking URL
    #[serde(rename = "TrackingUrl", skip_serializing_if = "Option::is_none")]
    pub tracking_url: Option<String>,
    /// Delivery option id of the external shipping provider
    #[serde(rename = "ExternalDeliveryOptionId", skip_serializing_if = "Option::is_none")]
    pub external_delivery_option_id: Option<String>,
    /// Service id of the external shipping provider
    #[serde(rename = "ExternalServiceId", skip_serializing_if = "Option::is_none")]
    pub external_service_id: Option<String>,
    /// Carrier id of the external shipping provider
    #[serde(rename = "ExternalCarrierId", skip_serializing_if = "Option::is_none")]
    pub external_carrier_id: Option<String>,
    /// Pickup point
    #[serde(rename = "PickupPoint", skip_serializing_if = "Option::is_none")]
    pub pickup_point: Option<String>,
}

impl OrderPeriodModelsPeriodShippingDetail {
    /// Data carrier for a shipping detail
    pub fn new() -> OrderPeriodModelsPeriodShippingDetail {
        OrderPeriodModelsPeriodShippingDetail {
            id: None,
            shipping_id: None,
            name: None,
            parcel_number: None,
            shipping_date: None,
            tracking_url: None,
            external_delivery_option_id: None,
            external_service_id: None,
            external_carrier_id: None,
            pickup_point: None,
        }
    }
}


