/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderPeriodCheckoutOrderRow {
    #[serde(rename = "Sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<String>,
    #[serde(rename = "ProductId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<i32>,
    #[serde(rename = "ExternalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "DiscountRate", skip_serializing_if = "Option::is_none")]
    pub discount_rate: Option<f64>,
    #[serde(rename = "CartRowId", skip_serializing_if = "Option::is_none")]
    pub cart_row_id: Option<i32>,
    #[serde(rename = "ProductContainerBuildId", skip_serializing_if = "Option::is_none")]
    pub product_container_build_id: Option<i32>,
    #[serde(rename = "Message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "ArticleNumber", skip_serializing_if = "Option::is_none")]
    pub article_number: Option<String>,
    #[serde(rename = "Gtin", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<String>,
    #[serde(rename = "Brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(rename = "Categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Variant", skip_serializing_if = "Option::is_none")]
    pub variant: Option<String>,
    #[serde(rename = "Quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
    #[serde(rename = "PriceIncVat", skip_serializing_if = "Option::is_none")]
    pub price_inc_vat: Option<f64>,
    #[serde(rename = "PriceExVat", skip_serializing_if = "Option::is_none")]
    pub price_ex_vat: Option<f64>,
    #[serde(rename = "ExpectedTotalPriceIncVat", skip_serializing_if = "Option::is_none")]
    pub expected_total_price_inc_vat: Option<f64>,
    #[serde(rename = "DiscountIncVat", skip_serializing_if = "Option::is_none")]
    pub discount_inc_vat: Option<f64>,
    #[serde(rename = "DiscountExVat", skip_serializing_if = "Option::is_none")]
    pub discount_ex_vat: Option<f64>,
    #[serde(rename = "ExpectedTotalDiscountIncVat", skip_serializing_if = "Option::is_none")]
    pub expected_total_discount_inc_vat: Option<f64>,
    #[serde(rename = "ProductUrl", skip_serializing_if = "Option::is_none")]
    pub product_url: Option<String>,
    #[serde(rename = "ImageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "Weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "Height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "Width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "Length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    #[serde(rename = "CampaignIds", skip_serializing_if = "Option::is_none")]
    pub campaign_ids: Option<Vec<String>>,
    #[serde(rename = "CampaignGroupData", skip_serializing_if = "Option::is_none")]
    pub campaign_group_data: Option<String>,
    #[serde(rename = "CampaignNames", skip_serializing_if = "Option::is_none")]
    pub campaign_names: Option<Vec<String>>,
    #[serde(rename = "ProductPriceCampaignId", skip_serializing_if = "Option::is_none")]
    pub product_price_campaign_id: Option<i32>,
    #[serde(rename = "ProductPriceListId", skip_serializing_if = "Option::is_none")]
    pub product_price_list_id: Option<i32>,
}

impl OrderPeriodCheckoutOrderRow {
    pub fn new() -> OrderPeriodCheckoutOrderRow {
        OrderPeriodCheckoutOrderRow {
            sku: None,
            product_id: None,
            external_id: None,
            discount_rate: None,
            cart_row_id: None,
            product_container_build_id: None,
            message: None,
            article_number: None,
            gtin: None,
            brand: None,
            categories: None,
            name: None,
            variant: None,
            quantity: None,
            price_inc_vat: None,
            price_ex_vat: None,
            expected_total_price_inc_vat: None,
            discount_inc_vat: None,
            discount_ex_vat: None,
            expected_total_discount_inc_vat: None,
            product_url: None,
            image_url: None,
            weight: None,
            height: None,
            width: None,
            length: None,
            campaign_ids: None,
            campaign_group_data: None,
            campaign_names: None,
            product_price_campaign_id: None,
            product_price_list_id: None,
        }
    }
}


