/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PageAreaPeriodModelsPeriodReadPeriodPageWidget : The API-representation of page widgets



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PageAreaPeriodModelsPeriodReadPeriodPageWidget {
    /// The IDs of widgets are immutable (determined by each view model implementation, in the namespace Carismar.Core)
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The static name of this widget. Used to translate into icons, or to append to css-classes.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The name of the widget-type
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Decides if this {PageArea.Models.Read.PageWidget} is active or not
    #[serde(rename = "Active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Holds all CSS Class names that this widget should render
    #[serde(rename = "ClassNames", skip_serializing_if = "Option::is_none")]
    pub class_names: Option<Vec<String>>,
    /// The fractional size for this widget in it's container.
    #[serde(rename = "Size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    /// The configuration for this {PageArea.Models.Read.PageWidget}
    #[serde(rename = "Configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
}

impl PageAreaPeriodModelsPeriodReadPeriodPageWidget {
    /// The API-representation of page widgets
    pub fn new() -> PageAreaPeriodModelsPeriodReadPeriodPageWidget {
        PageAreaPeriodModelsPeriodReadPeriodPageWidget {
            id: None,
            name: None,
            r#type: None,
            active: None,
            class_names: None,
            size: None,
            configuration: None,
        }
    }
}


