/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PageAreaPeriodModelsPeriodReadPeriodPageWidgetContainer : This class represents a collection of widgets, and defines how they should be layouted in the area they are rendered in.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PageAreaPeriodModelsPeriodReadPeriodPageWidgetContainer {
    /// The primary ID of this container
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The descriptive user defined name of this container, which is used to distinguish this container in a container library
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The CSS class names this container should use.
    #[serde(rename = "ClassNames", skip_serializing_if = "Option::is_none")]
    pub class_names: Option<Vec<String>>,
    #[serde(rename = "Active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "Layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<String>,
    #[serde(rename = "ResponsiveMode", skip_serializing_if = "Option::is_none")]
    pub responsive_mode: Option<String>,
    #[serde(rename = "Visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<String>,
    #[serde(rename = "Design", skip_serializing_if = "Option::is_none")]
    pub design: Option<String>,
    /// The configured widgets held by this container
    #[serde(rename = "Widgets", skip_serializing_if = "Option::is_none")]
    pub widgets: Option<Vec<crate::models::PageAreaPeriodModelsPeriodReadPeriodPageWidget>>,
}

impl PageAreaPeriodModelsPeriodReadPeriodPageWidgetContainer {
    /// This class represents a collection of widgets, and defines how they should be layouted in the area they are rendered in.
    pub fn new() -> PageAreaPeriodModelsPeriodReadPeriodPageWidgetContainer {
        PageAreaPeriodModelsPeriodReadPeriodPageWidgetContainer {
            id: None,
            name: None,
            class_names: None,
            active: None,
            layout: None,
            responsive_mode: None,
            visibility: None,
            design: None,
            widgets: None,
        }
    }
}


