/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentPeriodModelsPeriodPaymentOption {
    #[serde(rename = "PaymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<i32>,
    #[serde(rename = "PaymentGroupId", skip_serializing_if = "Option::is_none")]
    pub payment_group_id: Option<i32>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "DisplayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "Fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<f64>,
    #[serde(rename = "Icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "Sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<i32>,
    #[serde(rename = "Period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    #[serde(rename = "TermsLink", skip_serializing_if = "Option::is_none")]
    pub terms_link: Option<String>,
    #[serde(rename = "InfoLink", skip_serializing_if = "Option::is_none")]
    pub info_link: Option<String>,
    #[serde(rename = "PersonalIdRequired", skip_serializing_if = "Option::is_none")]
    pub personal_id_required: Option<bool>,
    #[serde(rename = "RegisteredAddressRequired", skip_serializing_if = "Option::is_none")]
    pub registered_address_required: Option<bool>,
    #[serde(rename = "HouseNumberRequired", skip_serializing_if = "Option::is_none")]
    pub house_number_required: Option<bool>,
    #[serde(rename = "HouseExtensionShown", skip_serializing_if = "Option::is_none")]
    pub house_extension_shown: Option<bool>,
    #[serde(rename = "GenderRequired", skip_serializing_if = "Option::is_none")]
    pub gender_required: Option<bool>,
    #[serde(rename = "BirthdateRequired", skip_serializing_if = "Option::is_none")]
    pub birthdate_required: Option<bool>,
}

impl PaymentPeriodModelsPeriodPaymentOption {
    pub fn new() -> PaymentPeriodModelsPeriodPaymentOption {
        PaymentPeriodModelsPeriodPaymentOption {
            payment_id: None,
            payment_group_id: None,
            name: None,
            display_name: None,
            fee: None,
            icon: None,
            sort: None,
            period: None,
            terms_link: None,
            info_link: None,
            personal_id_required: None,
            registered_address_required: None,
            house_number_required: None,
            house_extension_shown: None,
            gender_required: None,
            birthdate_required: None,
        }
    }
}


