/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProductPeriodModelsPeriodReadPeriodFeed : A product feed.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProductPeriodModelsPeriodReadPeriodFeed {
    /// The feed id.
    #[serde(rename = "FeedId", skip_serializing_if = "Option::is_none")]
    pub feed_id: Option<i32>,
    /// The feed name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The url to the feed.
    #[serde(rename = "Url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The name of the feed layout.
    #[serde(rename = "Layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<String>,
    /// The market of the feed.
    #[serde(rename = "Market", skip_serializing_if = "Option::is_none")]
    pub market: Option<i32>,
    /// The language code of the feed.
    #[serde(rename = "Language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// The default currency for the market
    #[serde(rename = "DefaultCurrency", skip_serializing_if = "Option::is_none")]
    pub default_currency: Option<String>,
    /// The default country for the market
    #[serde(rename = "DefaultCountry", skip_serializing_if = "Option::is_none")]
    pub default_country: Option<String>,
}

impl ProductPeriodModelsPeriodReadPeriodFeed {
    /// A product feed.
    pub fn new() -> ProductPeriodModelsPeriodReadPeriodFeed {
        ProductPeriodModelsPeriodReadPeriodFeed {
            feed_id: None,
            name: None,
            url: None,
            layout: None,
            market: None,
            language: None,
            default_currency: None,
            default_country: None,
        }
    }
}


