/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProductPeriodModelsPeriodWritePeriodProduct : A product.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProductPeriodModelsPeriodWritePeriodProduct {
    /// The article number of the product.
    #[serde(rename = "ArticleNumber", skip_serializing_if = "Option::is_none")]
    pub article_number: Option<String>,
    /// The localized names of the product.
    #[serde(rename = "Names", skip_serializing_if = "Option::is_none")]
    pub names: Option<Vec<crate::models::SharedPeriodModelsPeriodLocalizableContent>>,
    /// The current state of the product.
    #[serde(rename = "Active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// The purchase price in the currency defined in {Product.Models.Write.Product.PurchasePriceCurrency}.
    #[serde(rename = "PurchasePrice", skip_serializing_if = "Option::is_none")]
    pub purchase_price: Option<f64>,
    /// The 3-letter ISO 4217 currency code for the amount given in {Product.Models.Write.Product.PurchasePrice}.
    #[serde(rename = "PurchasePriceCurrency", skip_serializing_if = "Option::is_none")]
    pub purchase_price_currency: Option<String>,
    /// Localized short texts for the product.
    #[serde(rename = "ShortTexts", skip_serializing_if = "Option::is_none")]
    pub short_texts: Option<Vec<crate::models::SharedPeriodModelsPeriodLocalizableContent>>,
    /// Localized long texts for the product.
    #[serde(rename = "LongTexts", skip_serializing_if = "Option::is_none")]
    pub long_texts: Option<Vec<crate::models::SharedPeriodModelsPeriodLocalizableContent>>,
    /// Localized tech texts for the product.
    #[serde(rename = "TechTexts", skip_serializing_if = "Option::is_none")]
    pub tech_texts: Option<Vec<crate::models::SharedPeriodModelsPeriodLocalizableContent>>,
    /// The brand of the product.
    #[serde(rename = "BrandId", skip_serializing_if = "Option::is_none")]
    pub brand_id: Option<i32>,
    /// The supplier id of the product.
    #[serde(rename = "SupplierId", skip_serializing_if = "Option::is_none")]
    pub supplier_id: Option<i32>,
    /// The items belonging to the product.
    #[serde(rename = "Items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ProductPeriodModelsPeriodWritePeriodProductItem>>,
    /// The category ids the product belongs to.
    #[serde(rename = "CategoryIds", skip_serializing_if = "Option::is_none")]
    pub category_ids: Option<Vec<i32>>,
    /// The parameter values associated with the product.
    #[serde(rename = "ParameterValues", skip_serializing_if = "Option::is_none")]
    pub parameter_values: Option<Vec<crate::models::ProductParameterPeriodModelsPeriodWritePeriodProductParameterValue>>,
    /// The variants for this product.
    #[serde(rename = "Variants", skip_serializing_if = "Option::is_none")]
    pub variants: Option<Vec<crate::models::VariantPeriodModelsPeriodWritePeriodVariant>>,
    /// The markets for this product
    #[serde(rename = "Markets", skip_serializing_if = "Option::is_none")]
    pub markets: Option<Vec<crate::models::MarketPeriodModelsPeriodMarket>>,
    /// ID of freight class
    #[serde(rename = "FreightClassId", skip_serializing_if = "Option::is_none")]
    pub freight_class_id: Option<i32>,
    /// Intrastat code of the product
    #[serde(rename = "IntrastatCode", skip_serializing_if = "Option::is_none")]
    pub intrastat_code: Option<String>,
    /// Country of orgin of product
    #[serde(rename = "CountryOfOrigin", skip_serializing_if = "Option::is_none")]
    pub country_of_origin: Option<String>,
    /// ID of Variant Group to whom the product should be associated
    #[serde(rename = "VariantGroupId", skip_serializing_if = "Option::is_none")]
    pub variant_group_id: Option<i32>,
    /// ID or rate of VAT (On create and if no VAT is provided then default VAT will be used)
    #[serde(rename = "Vat", skip_serializing_if = "Option::is_none")]
    pub vat: Option<i32>,
    /// Defines how VAT parameter should be interpreted  Actual = VAT parameter is interpreted as VAT rate  VatId = VAT parameter is interpreted as VAT Id
    #[serde(rename = "VatType", skip_serializing_if = "Option::is_none")]
    pub vat_type: Option<String>,
    /// External Id of the product.
    #[serde(rename = "ExternalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// Activation date for the product.
    #[serde(rename = "ActivationDate", skip_serializing_if = "Option::is_none")]
    pub activation_date: Option<String>,
}

impl ProductPeriodModelsPeriodWritePeriodProduct {
    /// A product.
    pub fn new() -> ProductPeriodModelsPeriodWritePeriodProduct {
        ProductPeriodModelsPeriodWritePeriodProduct {
            article_number: None,
            names: None,
            active: None,
            purchase_price: None,
            purchase_price_currency: None,
            short_texts: None,
            long_texts: None,
            tech_texts: None,
            brand_id: None,
            supplier_id: None,
            items: None,
            category_ids: None,
            parameter_values: None,
            variants: None,
            markets: None,
            freight_class_id: None,
            intrastat_code: None,
            country_of_origin: None,
            variant_group_id: None,
            vat: None,
            vat_type: None,
            external_id: None,
            activation_date: None,
        }
    }
}


