/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProductPeriodModelsPeriodWritePeriodProductItem : A product item belonging to a product.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProductPeriodModelsPeriodWritePeriodProductItem {
    /// Id of the product item.
    #[serde(rename = "ItemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i32>,
    /// The article number for the product item.
    #[serde(rename = "ArticleNumber", skip_serializing_if = "Option::is_none")]
    pub article_number: Option<String>,
    /// The name of the product item.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The shelf name where the product item can be found.
    #[serde(rename = "Shelf", skip_serializing_if = "Option::is_none")]
    pub shelf: Option<String>,
    /// The weight of the item in grams (g).
    #[serde(rename = "Weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    /// The length of the item in millimeters (mm).
    #[serde(rename = "Length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    /// The width of the item in millimeters (mm).
    #[serde(rename = "Width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    /// The height of the item in millimeters (mm).
    #[serde(rename = "Height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// The GTIN number for the item.
    #[serde(rename = "Gtin", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<String>,
    /// The current state of the item.
    #[serde(rename = "Active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// External Id of the product item.
    #[serde(rename = "ExternalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
}

impl ProductPeriodModelsPeriodWritePeriodProductItem {
    /// A product item belonging to a product.
    pub fn new() -> ProductPeriodModelsPeriodWritePeriodProductItem {
        ProductPeriodModelsPeriodWritePeriodProductItem {
            item_id: None,
            article_number: None,
            name: None,
            shelf: None,
            weight: None,
            length: None,
            width: None,
            height: None,
            gtin: None,
            active: None,
            external_id: None,
        }
    }
}


