/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VariantPeriodModelsPeriodWritePeriodVariantGroup : A variant group for a collection of related variants.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VariantPeriodModelsPeriodWritePeriodVariantGroup {
    /// The optional internal name of the variant group.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A setting to control the display behaviour in product listings of variants belonging to this group.
    #[serde(rename = "CollapseInLists", skip_serializing_if = "Option::is_none")]
    pub collapse_in_lists: Option<bool>,
    /// The labels of the variant data that this group keeps track of
    #[serde(rename = "VariantLabels", skip_serializing_if = "Option::is_none")]
    pub variant_labels: Option<Vec<String>>,
    /// Products to be created and connected to the group.
    #[serde(rename = "Products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<crate::models::ProductPeriodModelsPeriodWritePeriodProduct>>,
}

impl VariantPeriodModelsPeriodWritePeriodVariantGroup {
    /// A variant group for a collection of related variants.
    pub fn new() -> VariantPeriodModelsPeriodWritePeriodVariantGroup {
        VariantPeriodModelsPeriodWritePeriodVariantGroup {
            name: None,
            collapse_in_lists: None,
            variant_labels: None,
            products: None,
        }
    }
}


